parameters:
    troopers_mangopay.mango_api.class: Troopers\MangopayBundle\Helper\MangopayHelper
    troopers_mangopay.payment_helper.class: Troopers\MangopayBundle\Helper\PaymentHelper
    troopers_mangopay.card_registration_helper.class: Troopers\MangopayBundle\Helper\CardRegistrationHelper
    troopers_mangopay.payment_direct_helper.class: Troopers\MangopayBundle\Helper\PaymentDirectHelper
    troopers_mangopay.payment_out_helper.class: Troopers\MangopayBundle\Helper\PaymentOutHelper
    troopers_mangopay.bankwire_helper.class: Troopers\MangopayBundle\Helper\BankwireHelper
    troopers_mangopay.user_helper.class: Troopers\MangopayBundle\Helper\UserHelper
    troopers_mangopay.user_legal_helper.class: Troopers\MangopayBundle\Helper\UserLegalHelper
    troopers_mangopay.bank_information_helper.class: Troopers\MangopayBundle\Helper\BankInformationHelper
    troopers_mangopay.wallet_helper.class: Troopers\MangopayBundle\Helper\WalletHelper
    troopers_mangopay.transaction_helper.class: Troopers\MangopayBundle\Helper\TransactionHelper
    troopers_mangopay.payment_transfer_helper.class: Troopers\MangopayBundle\Helper\PaymentTransferHelper
    troopers_mangopay.kyc_helper.class: Troopers\MangopayBundle\Helper\KycHelper
#    troopers_mangopay.order.class: Troopers\MangopayBundle\Entity\Order
    troopers_mangopay.form.card: Troopers\MangopayBundle\Form\Type\CardType

    troopers_mangopay.annotation_reader.class: Troopers\MangopayBundle\Annotation\MangoPayAnnotationReader
    troopers_mangopay.handler.class: Troopers\MangopayBundle\Handler\MangoPayHandler
    troopers_mangopay.subscriber.class: Troopers\MangopayBundle\Listener\MangoPaySubscriber

services:
    troopers_mangopay.mango_api:
        class: "%troopers_mangopay.mango_api.class%"
        arguments:
            - "%troopers_mangopay.client_id%"
            - "%troopers_mangopay.client_password%"
            - "%troopers_mangopay.base_url%"
            - "@event_dispatcher"
            - "@doctrine.orm.entity_manager"
            - "%troopers_mangopay.debug_mode%"

    troopers_mangopay.user_helper:
        class: "%troopers_mangopay.user_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - '@troopers_mangopay.user_legal_helper'

    troopers_mangopay.user_legal_helper:
        class: "%troopers_mangopay.user_legal_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    troopers_mangopay.bank_information_helper:
        class: "%troopers_mangopay.bank_information_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - "@doctrine.orm.entity_manager"
            - "@troopers_mangopay.user_helper"
            - "@event_dispatcher"

    troopers_mangopay.wallet_helper:
        class: "%troopers_mangopay.wallet_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - "@troopers_mangopay.user_helper"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"

    troopers_mangopay.card_registration_helper:
        class: "%troopers_mangopay.card_registration_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"

    troopers_mangopay.payment_helper:
        class: "%troopers_mangopay.payment_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - "@router"
            - "@event_dispatcher"
            - "@translator"

    troopers_mangopay.payment_direct_helper:
        class: "%troopers_mangopay.payment_direct_helper.class%"
        arguments:
            - "@service_container"
            - "@troopers_mangopay.mango_api"
            - "@troopers_mangopay.wallet_helper"
            - "@router"
            - "@event_dispatcher"

    troopers_mangopay.bankwire_helper:
        class: "%troopers_mangopay.bankwire_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - '@doctrine.orm.entity_manager'
            - '@troopers_mangopay.user_helper'
            - '@troopers_mangopay.wallet_helper'
            - '@event_dispatcher'
            - '@translator'

    troopers_mangopay.payment_out_helper:
        class: "%troopers_mangopay.payment_out_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"
            - '@doctrine.orm.entity_manager'
            - "@troopers_mangopay.wallet_helper"

    troopers_mangopay.transaction_helper:
        class: "%troopers_mangopay.transaction_helper.class%"
        arguments:
            - "@troopers_mangopay.mango_api"

    troopers_mangopay.payment_transfer_helper:
        class: "%troopers_mangopay.payment_transfer_helper.class%"
        arguments: ['@troopers_mangopay.mango_api', '@doctrine.orm.entity_manager', '@troopers_mangopay.wallet_helper']

    troopers_mangopay.kyc_helper:
        class: "%troopers_mangopay.kyc_helper.class%"
        arguments: ['@troopers_mangopay.mango_api', '@troopers_mangopay.user_helper', '@doctrine.orm.entity_manager', '@event_dispatcher']

    troopers_mangopay.form.card:
        class: "%troopers_mangopay.form.card%"
        tags:
            - { name: form.type }

    troopers_mangopay.annotation_reader:
        class: "%troopers_mangopay.annotation_reader.class%"
        arguments: ['@annotations.reader']

    troopers_mangopay.handler:
        class: "%troopers_mangopay.handler.class%"
        arguments:
            - '@service_container'

    troopers_mangopay.subscriber:
        class: "%troopers_mangopay.subscriber.class%"
        arguments: ['@troopers_mangopay.annotation_reader', '@troopers_mangopay.handler']
        tags:
            - { name: doctrine.event_subscriber, priority: -20}

    troopers_mangopay.exception_listener:
        class: Troopers\MangopayBundle\Listener\MangoPayExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    troopers_mangopay.data_transformer.date:
        class: Troopers\MangopayBundle\DataTransformer\TimestampTransformer
        tags:
            - { name: troopers_mangopay.data_transformer }

    troopers_mangopay.data_transformer.money:
        class: Troopers\MangopayBundle\DataTransformer\MoneyTransformer
        tags:
            - { name: troopers_mangopay.data_transformer }

